### ISSUE TITLE
Baud Rate initialisation needs to use formula from data sheet.

### ISSUE THREAD

**Issue by HarryBeadle** [d4thames/PPM-to-Digital-Converter#1]
The baud rate constant needs to be defined as per the datasheet. putting in 9600 will not result in 9600 baud - it is clock speed dependant.

**Comment by HarryBeadle** [comment]
p167 on the datasheet

**Comment by Strongo997** [comment]
I don't understand what you mean? The equation is on line 49 and 50 in PPMDECODER(fortesting).c  to calculate UBRR value just like in the datasheet.

**Comment by tim1997uk** [comment]
Did you use the equation to the left of that for the Baud Rate though? I think that's what Harry is referring to...?

Although looking at it I think it might be right....

**Comment by HarryBeadle** [comment]
Yeah apologies don't know where this came from
